### PR TITLE
Feat: Adjust `find_rej_files()` with argument for finding hidden .rej files

### PR DESCRIPTION
**Pull request by StephanLoor**
We currently aren't checking for hidden .rej files (i.e. filenames starting with `.`). This functionality is desirable, as the config of e.g. pre-commit hooks and cruft are maintained in hidden files by default. This PR adds this functionality.

### CODE REVIEW

**Review by MarkusSagen — COMMENTED** [review]
Thank you for proposing this change! 
It's a good suggestion, but could we add a flag to typer to optionally extend with the hidden files? The flag can be true by default to show hidden files, ex. `--show-hidden`?

**Comment by StephanLoor** [comment]
@MarkusSagen good idea - done!

**Comment by MarkusSagen** [comment]
Great change! Merging

**Comment by timvink** [comment]
@MarkusSagen Would you mind making a new release to pypi with these changes also? Latest version on pypi is 0.0.3 (https://pypi.org/project/rejx/#history)

**Comment by timvink** [comment]
@MarkusSagen sorry to ping you again.. would be great if you can make a pypi release

**Comment by MarkusSagen** [comment]
Sorry! Been a bit busy and had vacation
Aiming to make a new release this weekend

**Comment by MarkusSagen** [comment]
@timvink @StephanLoor Included now in the `0.2.0` release

**Comment by timvink** [comment]
Thanks!

**Pull request merged**
